/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VerifySignupRouteImport } from './routes/verify-signup'
import { Route as VerifyDeviceRouteImport } from './routes/verify-device'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DelivererRouteImport } from './routes/deliverer'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as WebhookFlutterwaveRouteImport } from './routes/webhook.flutterwave'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPostRouteImport } from './routes/admin.post'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminDeliveryPricesRouteImport } from './routes/admin.delivery-prices'
import { Route as AdminDeliverersRouteImport } from './routes/admin.deliverers'
import { Route as AccountYourOrdersRouteImport } from './routes/account.your-orders'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountMessagesRouteImport } from './routes/account.messages'
import { Route as AccountHistoryRouteImport } from './routes/account.history'
import { Route as AccountExpiredRouteImport } from './routes/account.expired'
import { Route as AccountEnrolledRouteImport } from './routes/account.enrolled'
import { Route as AccountEarnRouteImport } from './routes/account.earn'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as ProductIdReviewsRouteImport } from './routes/product_.$id.reviews'
import { Route as ApiPublicFlutterwaveWebhookRouteImport } from './routes/api/public/flutterwave-webhook'
import { Route as ApiPublicDeviceIdRouteImport } from './routes/api/public/device-id'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminActivePeriodRouteImport } from './routes/admin.active.$period'
import { Route as AccountRewardIdRouteImport } from './routes/account.reward.$id'
import { Route as AccountClaimIdRouteImport } from './routes/account.claim.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySignupRoute = VerifySignupRouteImport.update({
  id: '/verify-signup',
  path: '/verify-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyDeviceRoute = VerifyDeviceRouteImport.update({
  id: '/verify-device',
  path: '/verify-device',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DelivererRoute = DelivererRouteImport.update({
  id: '/deliverer',
  path: '/deliverer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const WebhookFlutterwaveRoute = WebhookFlutterwaveRouteImport.update({
  id: '/webhook/flutterwave',
  path: '/webhook/flutterwave',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostRoute = AdminPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryPricesRoute = AdminDeliveryPricesRouteImport.update({
  id: '/delivery-prices',
  path: '/delivery-prices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliverersRoute = AdminDeliverersRouteImport.update({
  id: '/deliverers',
  path: '/deliverers',
  getParentRoute: () => AdminRoute,
} as any)
const AccountYourOrdersRoute = AccountYourOrdersRouteImport.update({
  id: '/your-orders',
  path: '/your-orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMessagesRoute = AccountMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AccountRoute,
} as any)
const AccountExpiredRoute = AccountExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => AccountRoute,
} as any)
const AccountEnrolledRoute = AccountEnrolledRouteImport.update({
  id: '/enrolled',
  path: '/enrolled',
  getParentRoute: () => AccountRoute,
} as any)
const AccountEarnRoute = AccountEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdReviewsRoute = ProductIdReviewsRouteImport.update({
  id: '/product_/$id/reviews',
  path: '/product/$id/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlutterwaveWebhookRoute =
  ApiPublicFlutterwaveWebhookRouteImport.update({
    id: '/api/public/flutterwave-webhook',
    path: '/api/public/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeviceIdRoute = ApiPublicDeviceIdRouteImport.update({
  id: '/api/public/device-id',
  path: '/api/public/device-id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivePeriodRoute = AdminActivePeriodRouteImport.update({
  id: '/active/$period',
  path: '/active/$period',
  getParentRoute: () => AdminRoute,
} as any)
const AccountRewardIdRoute = AccountRewardIdRouteImport.update({
  id: '/reward/$id',
  path: '/reward/$id',
  getParentRoute: () => AccountRoute,
} as any)
const AccountClaimIdRoute = AccountClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/deliverer': typeof DelivererRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/verify-signup': typeof VerifySignupRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/earn': typeof AccountEarnRoute
  '/account/enrolled': typeof AccountEnrolledRoute
  '/account/expired': typeof AccountExpiredRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/messages': typeof AccountMessagesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/account/your-orders': typeof AccountYourOrdersRoute
  '/admin/deliverers': typeof AdminDeliverersRoute
  '/admin/delivery-prices': typeof AdminDeliveryPricesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/post': typeof AdminPostRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/search': typeof AdminSearchRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/webhook/flutterwave': typeof WebhookFlutterwaveRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/account/claim/$id': typeof AccountClaimIdRoute
  '/account/reward/$id': typeof AccountRewardIdRoute
  '/admin/active/$period': typeof AdminActivePeriodRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/device-id': typeof ApiPublicDeviceIdRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/product/$id/reviews': typeof ProductIdReviewsRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/deliverer': typeof DelivererRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/verify-signup': typeof VerifySignupRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/earn': typeof AccountEarnRoute
  '/account/enrolled': typeof AccountEnrolledRoute
  '/account/expired': typeof AccountExpiredRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/messages': typeof AccountMessagesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/account/your-orders': typeof AccountYourOrdersRoute
  '/admin/deliverers': typeof AdminDeliverersRoute
  '/admin/delivery-prices': typeof AdminDeliveryPricesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/post': typeof AdminPostRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/search': typeof AdminSearchRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/webhook/flutterwave': typeof WebhookFlutterwaveRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/account/claim/$id': typeof AccountClaimIdRoute
  '/account/reward/$id': typeof AccountRewardIdRoute
  '/admin/active/$period': typeof AdminActivePeriodRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/device-id': typeof ApiPublicDeviceIdRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/product/$id/reviews': typeof ProductIdReviewsRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/deliverer': typeof DelivererRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/verify-signup': typeof VerifySignupRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/earn': typeof AccountEarnRoute
  '/account/enrolled': typeof AccountEnrolledRoute
  '/account/expired': typeof AccountExpiredRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/messages': typeof AccountMessagesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/account/your-orders': typeof AccountYourOrdersRoute
  '/admin/deliverers': typeof AdminDeliverersRoute
  '/admin/delivery-prices': typeof AdminDeliveryPricesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/post': typeof AdminPostRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/search': typeof AdminSearchRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/webhook/flutterwave': typeof WebhookFlutterwaveRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/account/claim/$id': typeof AccountClaimIdRoute
  '/account/reward/$id': typeof AccountRewardIdRoute
  '/admin/active/$period': typeof AdminActivePeriodRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/device-id': typeof ApiPublicDeviceIdRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/product_/$id/reviews': typeof ProductIdReviewsRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/deliverer'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/verify-device'
    | '/verify-signup'
    | '/wishlist'
    | '/account/addresses'
    | '/account/earn'
    | '/account/enrolled'
    | '/account/expired'
    | '/account/history'
    | '/account/messages'
    | '/account/notifications'
    | '/account/settings'
    | '/account/wishlist'
    | '/account/your-orders'
    | '/admin/deliverers'
    | '/admin/delivery-prices'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/post'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/rewards'
    | '/admin/search'
    | '/orders/$id'
    | '/product/$id'
    | '/webhook/flutterwave'
    | '/account/'
    | '/admin/'
    | '/orders/'
    | '/account/claim/$id'
    | '/account/reward/$id'
    | '/admin/active/$period'
    | '/admin/users/$userId'
    | '/api/public/device-id'
    | '/api/public/flutterwave-webhook'
    | '/product/$id/reviews'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/deliverer'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/verify-device'
    | '/verify-signup'
    | '/wishlist'
    | '/account/addresses'
    | '/account/earn'
    | '/account/enrolled'
    | '/account/expired'
    | '/account/history'
    | '/account/messages'
    | '/account/notifications'
    | '/account/settings'
    | '/account/wishlist'
    | '/account/your-orders'
    | '/admin/deliverers'
    | '/admin/delivery-prices'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/post'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/rewards'
    | '/admin/search'
    | '/orders/$id'
    | '/product/$id'
    | '/webhook/flutterwave'
    | '/account'
    | '/admin'
    | '/orders'
    | '/account/claim/$id'
    | '/account/reward/$id'
    | '/admin/active/$period'
    | '/admin/users/$userId'
    | '/api/public/device-id'
    | '/api/public/flutterwave-webhook'
    | '/product/$id/reviews'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/deliverer'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/verify-device'
    | '/verify-signup'
    | '/wishlist'
    | '/account/addresses'
    | '/account/earn'
    | '/account/enrolled'
    | '/account/expired'
    | '/account/history'
    | '/account/messages'
    | '/account/notifications'
    | '/account/settings'
    | '/account/wishlist'
    | '/account/your-orders'
    | '/admin/deliverers'
    | '/admin/delivery-prices'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/post'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/rewards'
    | '/admin/search'
    | '/orders/$id'
    | '/product/$id'
    | '/webhook/flutterwave'
    | '/account/'
    | '/admin/'
    | '/orders/'
    | '/account/claim/$id'
    | '/account/reward/$id'
    | '/admin/active/$period'
    | '/admin/users/$userId'
    | '/api/public/device-id'
    | '/api/public/flutterwave-webhook'
    | '/product_/$id/reviews'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DelivererRoute: typeof DelivererRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  VerifyDeviceRoute: typeof VerifyDeviceRoute
  VerifySignupRoute: typeof VerifySignupRoute
  WishlistRoute: typeof WishlistRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductIdRoute: typeof ProductIdRoute
  WebhookFlutterwaveRoute: typeof WebhookFlutterwaveRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiPublicDeviceIdRoute: typeof ApiPublicDeviceIdRoute
  ApiPublicFlutterwaveWebhookRoute: typeof ApiPublicFlutterwaveWebhookRoute
  ProductIdReviewsRoute: typeof ProductIdReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-signup': {
      id: '/verify-signup'
      path: '/verify-signup'
      fullPath: '/verify-signup'
      preLoaderRoute: typeof VerifySignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-device': {
      id: '/verify-device'
      path: '/verify-device'
      fullPath: '/verify-device'
      preLoaderRoute: typeof VerifyDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverer': {
      id: '/deliverer'
      path: '/deliverer'
      fullPath: '/deliverer'
      preLoaderRoute: typeof DelivererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/webhook/flutterwave': {
      id: '/webhook/flutterwave'
      path: '/webhook/flutterwave'
      fullPath: '/webhook/flutterwave'
      preLoaderRoute: typeof WebhookFlutterwaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/post': {
      id: '/admin/post'
      path: '/post'
      fullPath: '/admin/post'
      preLoaderRoute: typeof AdminPostRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery-prices': {
      id: '/admin/delivery-prices'
      path: '/delivery-prices'
      fullPath: '/admin/delivery-prices'
      preLoaderRoute: typeof AdminDeliveryPricesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deliverers': {
      id: '/admin/deliverers'
      path: '/deliverers'
      fullPath: '/admin/deliverers'
      preLoaderRoute: typeof AdminDeliverersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/your-orders': {
      id: '/account/your-orders'
      path: '/your-orders'
      fullPath: '/account/your-orders'
      preLoaderRoute: typeof AccountYourOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/messages': {
      id: '/account/messages'
      path: '/messages'
      fullPath: '/account/messages'
      preLoaderRoute: typeof AccountMessagesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/history': {
      id: '/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/expired': {
      id: '/account/expired'
      path: '/expired'
      fullPath: '/account/expired'
      preLoaderRoute: typeof AccountExpiredRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/enrolled': {
      id: '/account/enrolled'
      path: '/enrolled'
      fullPath: '/account/enrolled'
      preLoaderRoute: typeof AccountEnrolledRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/earn': {
      id: '/account/earn'
      path: '/earn'
      fullPath: '/account/earn'
      preLoaderRoute: typeof AccountEarnRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product_/$id/reviews': {
      id: '/product_/$id/reviews'
      path: '/product/$id/reviews'
      fullPath: '/product/$id/reviews'
      preLoaderRoute: typeof ProductIdReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flutterwave-webhook': {
      id: '/api/public/flutterwave-webhook'
      path: '/api/public/flutterwave-webhook'
      fullPath: '/api/public/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device-id': {
      id: '/api/public/device-id'
      path: '/api/public/device-id'
      fullPath: '/api/public/device-id'
      preLoaderRoute: typeof ApiPublicDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/active/$period': {
      id: '/admin/active/$period'
      path: '/active/$period'
      fullPath: '/admin/active/$period'
      preLoaderRoute: typeof AdminActivePeriodRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/reward/$id': {
      id: '/account/reward/$id'
      path: '/reward/$id'
      fullPath: '/account/reward/$id'
      preLoaderRoute: typeof AccountRewardIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/claim/$id': {
      id: '/account/claim/$id'
      path: '/claim/$id'
      fullPath: '/account/claim/$id'
      preLoaderRoute: typeof AccountClaimIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountEarnRoute: typeof AccountEarnRoute
  AccountEnrolledRoute: typeof AccountEnrolledRoute
  AccountExpiredRoute: typeof AccountExpiredRoute
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountMessagesRoute: typeof AccountMessagesRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountYourOrdersRoute: typeof AccountYourOrdersRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountClaimIdRoute: typeof AccountClaimIdRoute
  AccountRewardIdRoute: typeof AccountRewardIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountEarnRoute: AccountEarnRoute,
  AccountEnrolledRoute: AccountEnrolledRoute,
  AccountExpiredRoute: AccountExpiredRoute,
  AccountHistoryRoute: AccountHistoryRoute,
  AccountMessagesRoute: AccountMessagesRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountYourOrdersRoute: AccountYourOrdersRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountClaimIdRoute: AccountClaimIdRoute,
  AccountRewardIdRoute: AccountRewardIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminDeliverersRoute: typeof AdminDeliverersRoute
  AdminDeliveryPricesRoute: typeof AdminDeliveryPricesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPostRoute: typeof AdminPostRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminActivePeriodRoute: typeof AdminActivePeriodRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDeliverersRoute: AdminDeliverersRoute,
  AdminDeliveryPricesRoute: AdminDeliveryPricesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPostRoute: AdminPostRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminActivePeriodRoute: AdminActivePeriodRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DelivererRoute: DelivererRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  VerifyDeviceRoute: VerifyDeviceRoute,
  VerifySignupRoute: VerifySignupRoute,
  WishlistRoute: WishlistRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductIdRoute: ProductIdRoute,
  WebhookFlutterwaveRoute: WebhookFlutterwaveRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiPublicDeviceIdRoute: ApiPublicDeviceIdRoute,
  ApiPublicFlutterwaveWebhookRoute: ApiPublicFlutterwaveWebhookRoute,
  ProductIdReviewsRoute: ProductIdReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
